/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utsfitria;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agnes-PC
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel2 = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rbEkonomi = new javax.swing.JRadioButton();
        txtWaktu = new javax.swing.JComboBox<>();
        txtStaAwal = new javax.swing.JComboBox<>();
        rbEksekutif = new javax.swing.JRadioButton();
        txtStaTujuan = new javax.swing.JComboBox<>();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        txtNo = new javax.swing.JTextField();
        txtDuduk = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        panel2.setBackground(new java.awt.Color(102, 102, 255));
        panel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 29)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pemesanan Tiket Kereta Api");
        panel2.add(jLabel12);
        jLabel12.setBounds(210, 10, 370, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Blitar - Malang ");
        panel2.add(jLabel2);
        jLabel2.setBounds(310, 40, 210, 40);

        getContentPane().add(panel2);
        panel2.setBounds(0, 0, 740, 90);

        panel1.setBackground(new java.awt.Color(153, 255, 255));
        panel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Nama Pemesan");
        panel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 104, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("NO ID");
        panel1.add(jLabel5);
        jLabel5.setBounds(20, 10, 104, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Stasiun Tujuan ");
        panel1.add(jLabel7);
        jLabel7.setBounds(20, 130, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Tanggal Berangkat");
        panel1.add(jLabel8);
        jLabel8.setBounds(20, 170, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Jenis Kereta");
        panel1.add(jLabel9);
        jLabel9.setBounds(350, 10, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Tempat Duduk");
        panel1.add(jLabel11);
        jLabel11.setBounds(350, 140, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Harga");
        panel1.add(jLabel3);
        jLabel3.setBounds(350, 170, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Stasiun Awal");
        panel1.add(jLabel6);
        jLabel6.setBounds(20, 90, 100, 30);

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        panel1.add(txtNama);
        txtNama.setBounds(150, 50, 190, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Waktu Berangkat");
        panel1.add(jLabel10);
        jLabel10.setBounds(350, 90, 160, 40);

        buttonGroup1.add(rbEkonomi);
        rbEkonomi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbEkonomi.setText("Ekonomi");
        rbEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEkonomiActionPerformed(evt);
            }
        });
        panel1.add(rbEkonomi);
        rbEkonomi.setBounds(350, 50, 100, 30);

        txtWaktu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "05.00", "07.00", "10.00", "14.30", "17.00", "19.00", "20.30" }));
        txtWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaktuActionPerformed(evt);
            }
        });
        panel1.add(txtWaktu);
        txtWaktu.setBounds(490, 100, 130, 30);

        txtStaAwal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStaAwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blitar", "Garum", "Talun", "Wlingi", "Kesamben", "Pohgajeh", "Sumberpucung", "Ngebruk", "Kepanjen", "Kota Lama", "Kota Baru" }));
        panel1.add(txtStaAwal);
        txtStaAwal.setBounds(150, 90, 150, 30);

        buttonGroup1.add(rbEksekutif);
        rbEksekutif.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbEksekutif.setText("Eksekutif");
        rbEksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEksekutifActionPerformed(evt);
            }
        });
        panel1.add(rbEksekutif);
        rbEksekutif.setBounds(470, 50, 100, 30);

        txtStaTujuan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtStaTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blitar", "Garum", "Talun", "Wlingi", "Kesamben", "Pohgajeh", "Sumberpucung", "Ngebruk", "Kepanjen", "Kota Lama", "Kota Baru" }));
        panel1.add(txtStaTujuan);
        txtStaTujuan.setBounds(150, 130, 150, 30);
        panel1.add(txtTanggal);
        txtTanggal.setBounds(150, 170, 170, 30);

        txtNo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        panel1.add(txtNo);
        txtNo.setBounds(150, 10, 130, 30);

        txtDuduk.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5" }));
        panel1.add(txtDuduk);
        txtDuduk.setBounds(490, 140, 130, 30);

        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        panel1.add(txtHarga);
        txtHarga.setBounds(490, 180, 130, 30);

        getContentPane().add(panel1);
        panel1.setBounds(0, 100, 640, 220);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("See data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(650, 260, 90, 40);

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(650, 210, 90, 40);

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(650, 160, 90, 40);

        jButton4.setBackground(new java.awt.Color(0, 51, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Price");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(650, 110, 90, 40);

        setSize(new java.awt.Dimension(757, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEkonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEkonomiActionPerformed

    private void rbEksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEksekutifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEksekutifActionPerformed

    private void txtWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        frmData a = new frmData();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         txtNama.setText("");
        txtNo.setText("");
        txtHarga.setText("");
        buttonGroup1.clearSelection();
        txtStaAwal.setSelectedIndex(0);
        txtStaTujuan.setSelectedIndex(0);
        txtWaktu.setSelectedIndex(0);
        txtDuduk.setSelectedIndex(0);
        txtTanggal.setCalendar(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(txtTanggal.getDate());
        
        String JK = "";
        if(rbEkonomi.isSelected()) 
            {
                JK = "Ekonomi";
            }
            else
            {
                JK = "Eksekutif";
            }
        if("".equals(txtNo.getText()) || "".equals(txtNama.getText()) || "".equals(txtStaAwal.getSelectedItem()) || "".equals(txtStaTujuan.getSelectedItem()) || tanggal.equals("") || "".equals(txtWaktu.getSelectedItem()) || JK.equals("") || "".equals(txtDuduk.getSelectedItem())) 
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
        }  else 
        {      
            String SQL = "INSERT INTO tb_pesan (noID,namaPemesan,stasiunAwal,stasiunTujuan,tanggalBerangkat,jenisKereta,waktuBerangkat,tempatDuduk,Harga)"
                + "VALUES('"+txtNo.getText()+"','"+txtNama.getText()+"','"+txtStaAwal.getSelectedItem()+"','"+txtStaTujuan.getSelectedItem()+"','"+tanggal+"','"+JK+"','"+txtWaktu.getSelectedItem()+"','"+txtDuduk.getSelectedItem()+"','"+txtHarga.getText()+"')";
        int status = 0;
             try {
                 status = dbKoneksi.execute(SQL);
             } catch (SQLException ex) {
                 Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
             }
        if(status == 1){
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
   
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String rupiah ="";
        if(rbEkonomi.isSelected()) 
            {
                rupiah = "15000";
            }
            else
            {
                rupiah = "85000";
            }
        txtHarga.setText(rupiah);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JRadioButton rbEkonomi;
    private javax.swing.JRadioButton rbEksekutif;
    private javax.swing.JComboBox<String> txtDuduk;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JComboBox<String> txtStaAwal;
    private javax.swing.JComboBox<String> txtStaTujuan;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JComboBox<String> txtWaktu;
    // End of variables declaration//GEN-END:variables

 
}
